apiVersion: v1
kind: Service
metadata:
  name: fluttermusic-web
spec:
  type: NodePort
  selector:
    app: fluttermusic-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluttermusic-web
  labels:
    app: fluttermusic-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluttermusic-web
  template:
    metadata:
      labels:
        app: fluttermusic-web
    spec:
      containers:
        - name: fluttermusic-web
          image: rihabbennour/fluttermusic-web:latest
          ports:
            - containerPort: 80
